### ISSUE TITLE
Async Web in Unity3D

### ISSUE THREAD

**Issue by HelloKitty** [Error22/PokemonGo-Desktop#3]
Hi guys, I'm working on a Unity3D port of Pokemon Go too.

I've built an async layer on top of RESTSharp in Unity3D and built a coroutine service to deal with it. It looks like you're headed in a similar direction. Might I recommend adopting my library for that? I don't have the Unity3D API on Nuget but I do have my PokemonGoDesktop.API on Nuget which offers better compiled proto defs than POGOProtos default.

You may find it useful.

**Comment by csnewman** [comment]
Thanks for the suggestion however at the moment I am not looking to migrate to a different API at the moment. With how volatile the APIs are for the game and the pace at which we are learning new things, I think that relyling on an API may be slow down progress. Thanks for the suggestion however!
